"""added adhaar

Revision ID: 0c0e94b46ca4
Revises: 21b97631d372
Create Date: 2023-01-29 09:41:55.615426

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c0e94b46ca4"
down_revision = "21b97631d372"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.alter_column("farm", "country", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("farm", "state", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column("users", sa.Column("adhaar", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["adhaar"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "adhaar")
    op.alter_column("farm", "state", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("farm", "country", existing_type=sa.VARCHAR(), nullable=True)
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
