"""update_disease_table

Revision ID: 76161efe25c0
Revises: 05b11f925f4a
Create Date: 2023-02-07 01:15:11.673000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76161efe25c0"
down_revision = "05b11f925f4a"
branch_labels = None
depends_on = None
table_name = "disease"


def upgrade() -> None:
    op.drop_column(table_name, "description")
    op.drop_column(table_name, "diesease_type")
    op.drop_column(table_name, "afftected_plants")
    op.drop_column(table_name, "images")
    op.drop_column(table_name, "causes")
    op.add_column(table_name, sa.Column("pre", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("folder_name", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("file_format", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("affected_plant", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("causes", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image1", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image2", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image3", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image4", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image5", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image6", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image7", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image8", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image9", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image10", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image11", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image12", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image13", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image14", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image15", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image16", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image17", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image18", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image19", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image20", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image21", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image22", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image23", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image24", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image25", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image26", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image27", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image28", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image29", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image30", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image31", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image32", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image33", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image34", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image35", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image36", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image37", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image38", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image39", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image40", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image41", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image42", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image43", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image44", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image45", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image46", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image47", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image48", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image49", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image50", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image51", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image52", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image53", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image54", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image55", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image56", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image57", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image58", sa.String(), nullable=True))
    op.add_column(table_name, sa.Column("image59", sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column(table_name, "pre")
    op.drop_column(table_name, "folder_name")
    op.drop_column(table_name, "file_format")
    op.drop_column(table_name, "affected_plant")
    op.drop_column(table_name, "image1")
    op.drop_column(table_name, "image2")
    op.drop_column(table_name, "image3")
    op.drop_column(table_name, "image4")
    op.drop_column(table_name, "image5")
    op.drop_column(table_name, "image6")
    op.drop_column(table_name, "image7")
    op.drop_column(table_name, "image8")
    op.drop_column(table_name, "image9")
    op.drop_column(table_name, "image10")
    op.drop_column(table_name, "image11")
    op.drop_column(table_name, "image12")
    op.drop_column(table_name, "image13")
    op.drop_column(table_name, "image14")
    op.drop_column(table_name, "image15")
    op.drop_column(table_name, "image16")
    op.drop_column(table_name, "image17")
    op.drop_column(table_name, "image18")
    op.drop_column(table_name, "image19")
    op.drop_column(table_name, "image20")
    op.drop_column(table_name, "image21")
    op.drop_column(table_name, "image22")
    op.drop_column(table_name, "image23")
    op.drop_column(table_name, "image24")
    op.drop_column(table_name, "image25")
    op.drop_column(table_name, "image26")
    op.drop_column(table_name, "image27")
    op.drop_column(table_name, "image28")
    op.drop_column(table_name, "image29")
    op.drop_column(table_name, "image30")
    op.drop_column(table_name, "image31")
    op.drop_column(table_name, "image32")
    op.drop_column(table_name, "image33")
    op.drop_column(table_name, "image34")
    op.drop_column(table_name, "image35")
    op.drop_column(table_name, "image36")
    op.drop_column(table_name, "image37")
    op.drop_column(table_name, "image38")
    op.drop_column(table_name, "image39")
    op.drop_column(table_name, "image40")
    op.drop_column(table_name, "image41")
    op.drop_column(table_name, "image42")
    op.drop_column(table_name, "image43")
    op.drop_column(table_name, "image44")
    op.drop_column(table_name, "image45")
    op.drop_column(table_name, "image46")
    op.drop_column(table_name, "image47")
    op.drop_column(table_name, "image48")
    op.drop_column(table_name, "image49")
    op.drop_column(table_name, "image50")
    op.drop_column(table_name, "image51")
    op.drop_column(table_name, "image52")
    op.drop_column(table_name, "image53")
    op.drop_column(table_name, "image54")
    op.drop_column(table_name, "image55")
    op.drop_column(table_name, "image56")
    op.drop_column(table_name, "image57")
    op.drop_column(table_name, "image58")
    op.drop_column(table_name, "image59")
