import enum


class Events(enum.Enum):
    NEW_FARMER_ADDED = "NEW_FARMER_ADDED"
    NEW_FARM_ADDED = "NEW_FARM_ADD"
    NEW_COMPANY_ADDED = "NEW_COMPANY_ADDED"
    NEW_SCOUTING_ADDED = "NEW_SCOUTING_ADDED"
    FARM_PAYMENT_UPDATED = "FARM_PAYMENT_UPDATED"
    NON_ACTIVE_USER = "NON_ACTIVE_USER"
    PAYING_FARMER = "PAYING_FARMER"
    ENTERPRISE_USERS = "ENTERPRISE_USERS"
    FARM_CROP_ADDED = "FARM_CROP_ADDED"
    COUNTRYWISE_USER = "COUNTRYWISE_USER"
